### PR TITLE
Added scheduled database imports

### PR DESCRIPTION
**Pull request by lonewolf9277**
The command "python manage.py schedule" will schedule a job to fetch json and update database on a weekly basis.

### CODE REVIEW

**Comment by tarxvftech** [comment]
Good stuff! I'll get this merged in tonight later tonight :D

**Comment by tarxvftech** [comment]
okay, not tonight I guess. Life got in the way.

But I think the label should make sure it counts and I'll have it merged before the end of the month regardless. Thanks for the work, it looks great and I can't wait to demo it to some local amateur radio club website admins!

**Comment by lonewolf9277** [comment]
Sure thanks glad it's working as expected.

**Comment by tarxvftech** [comment]
Awesome work, thank you!

**Pull request merged**
