### PR TITLE
Joe

### PR DESCRIPTION
**Pull request by Josephtobi**
i think i finally figured it out

### CODE REVIEW

**Comment by tarxvftech** [comment]
Looks good, thanks for making those changes! 
I'll take a closer look in a few hours to test it on my end and then merge it (just need to wake up first).

**Comment by tarxvftech** [comment]
Successfully created a repeater entry in my local DB with
`curl http://127.0.0.1:8080/api/repeater/ -X POST -u mike:test --json '{"callsign":"w2fbi","lat":42, "lon":-70, "alt":0, "access_information":"PL 67", "tags":[1], "freq":[1]}'` where the `1`s are PKs of existing entries for tags and a frequency pair, so this requires frequencies and such to be created beforehand of course. 

Sweet!

**Comment by Josephtobi** [comment]
Yay
So excited about this.

If you need anything with django and django rest framework I would love to
jump on it.

**Comment by tarxvftech** [comment]
It's live on the site, thank you! :D

Want to keep working on the API? 
* [ ] GET views - lists and individual
* [ ] associating the created repeater with the user that created it with the owner field
* [ ] PUTs on existing repeaters with replacement data

bonus points with examples of each operation with curl, or better yet a django test! :grin:

**Comment by Josephtobi** [comment]
What do you mean by django test
Like a mini api doc?
I can spin off a swagger doc

**Comment by tarxvftech** [comment]
django has it's own testing [capabilities](https://docs.djangoproject.com/en/3.2/topics/testing/overview), which include a test database. It's a handy way to make sure thing work like you might expect (such as checking that only the owner of a repeater can edit it).

**Pull request merged**
